/**
 * Copyright (c) 2025 Webapp Software Solutions. All rights reserved.
 * This file belongs to Webapp Software Solutions and is proprietary and confidential.
 * Unauthorized copying of this file, via any medium is strictly prohibited.
 * Website: https://webappssoft.com
 */

export enum BankType {
  SAVINGS = 'SAVINGS',
  CURRENT = 'CURRENT',
  SALARY = 'SALARY',
  FIXED_DEPOSIT = 'FIXED_DEPOSIT',
  RECURRING_DEPOSIT = 'RECURRING_DEPOSIT',
  NRI = 'NRI',
  JOINT = 'JOINT',
}

export enum AccountStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  FROZEN = 'FROZEN',
  CLOSED = 'CLOSED',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
}

export enum BankName {
  SBI = 'STATE_BANK_OF_INDIA',
  HDFC = 'HDFC_BANK',
  ICICI = 'ICICI_BANK',
  AXIS = 'AXIS_BANK',
  KOTAK = 'KOTAK_MAHINDRA_BANK',
  PNB = 'PUNJAB_NATIONAL_BANK',
  BOB = 'BANK_OF_BARODA',
  CANARA = 'CANARA_BANK',
  UNION = 'UNION_BANK_OF_INDIA',
  INDIAN = 'INDIAN_BANK',
  BOI = 'BANK_OF_INDIA',
  CENTRAL = 'CENTRAL_BANK_OF_INDIA',
  IDBI = 'IDBI_BANK',
  YES = 'YES_BANK',
  INDUSIND = 'INDUSIND_BANK',
  FEDERAL = 'FEDERAL_BANK',
  SOUTH_INDIAN = 'SOUTH_INDIAN_BANK',
  KARUR_VYSYA = 'KARUR_VYSYA_BANK',
  CITY_UNION = 'CITY_UNION_BANK',
  BANDHAN = 'BANDHAN_BANK',
  RBL = 'RBL_BANK',
  DCB = 'DCB_BANK',
  IDFC_FIRST = 'IDFC_FIRST_BANK',
  EQUITAS = 'EQUITAS_SMALL_FINANCE_BANK',
  AU_SMALL = 'AU_SMALL_FINANCE_BANK',
  UJJIVAN = 'UJJIVAN_SMALL_FINANCE_BANK',
  PAYTM = 'PAYTM_PAYMENTS_BANK',
  AIRTEL = 'AIRTEL_PAYMENTS_BANK',
  FINO = 'FINO_PAYMENTS_BANK',
  JANALAKSHMI = 'JANALAKSHMI_SMALL_FINANCE_BANK',
  CAPITAL_SMALL = 'CAPITAL_SMALL_FINANCE_BANK',
  ESAF = 'ESAF_SMALL_FINANCE_BANK',
  NORTH_EAST = 'NORTH_EAST_SMALL_FINANCE_BANK',
  SURYODAY = 'SURYODAY_SMALL_FINANCE_BANK',
  UTKARSH = 'UTKARSH_SMALL_FINANCE_BANK',
  OTHER = 'OTHER',
}
